### ISSUE TITLE
PlaceholderAPI registration

### ISSUE THREAD

**Issue by Ledovecek** [Tanguygab/AFKPlaytime#1]
Your plugin does not register placeholders.

**Comment by Ledovecek** [comment]
Add code below in `onEnable()` method:

`if (getServer().getPluginManager().isPluginEnabled("PlaceholderAPI")) {
            expansion = new AFKPlaytimeExpansion(this);
            expansion.register();
}`
    

And `plugin.yml` should have `depend: [Essentials, PlaceholderAPI]`

**Comment by Tanguygab** [comment]
Ah that's what I was missing, thanks 😅
